services:
  mongodb:
    container_name: mongodb
    image: mongo:8.0.3
    volumes:
      - mongodbdata:/data/db
    env_file:
      - ./env/mongo.env
    ports:
      - "27017:27017"
    networks:
      - db-net

  api:
    container_name: nodeapp
    depends_on:
      - mongodb
    build:
      context: ./API-jokes
      dockerfile: Dockerfile
    image: node-api-image
    ports:
      - "5000:5000"
    env_file:
      - ./env/server.env
    networks:
      - db-net
      - server-net
    develop:
      watch:
        - path: ./API-jokes
          action: sync
          target: /app
          ignore:
            - .git
            - node_modules
  client:
    stdin_open: true
    tty: true
    container_name: reactapp
    depends_on:
      - api
    build:
      context: ./react-client
      dockerfile: Dockerfile.prod
    image: react-client-image
    ports:
      - "80:80"
    env_file:
      - ./env/server.env
    networks:
      - server-net
    develop:
      watch:
        - path: ./react-client
          action: sync
          target: /app
          ignore:
            - .git
            - node_modules
            - dist
    

volumes:
  mongodbdata:

networks:
  db-net:
  server-net:
